export const THEME = {
  light: {
    accent: "#15784d",
    appBg: "bg-slate-100",
    headerCls: "glass-header-light",
    blockCls: "glass-light",
    blockHd: "glass-bar-light text-slate-800",
    blockBtn: "bg-white/30 hover:bg-white/55 text-slate-700 border border-white/50",
    tblHead: "bg-white/18 text-slate-500 border-b border-white/35",
    tblRow: "bg-white/12 border-b border-white/22",
    tblHover: "hover:bg-white/32",
    formCard: "glass-light rounded-xl",
    formLabel: "text-slate-700",
    inputCls: "bg-white/35 border-white/50 text-slate-800 focus:ring-emerald-600 focus:bg-white/55",
    modalCls: "glass-modal-light",
    overlay: "bg-slate-900/18 backdrop-blur-sm",
    textPri: "text-slate-900",
    textSec: "text-slate-500",
    textMut: "text-slate-400",
    accentText: "text-emerald-700",
    btnPri: "bg-emerald-700 hover:bg-emerald-800 text-white shadow-sm shadow-emerald-900/20",
    btnSec: "bg-white/32 hover:bg-white/52 text-slate-700 border border-white/50",
    btnGreen: "bg-emerald-700 hover:bg-emerald-800 text-white shadow-sm shadow-emerald-900/20",
    btnDanger: "bg-rose-500/12 hover:bg-rose-500/22 text-rose-600 border border-rose-400/28",
    tabActive: "bg-emerald-700 text-white shadow-sm shadow-emerald-900/25",
    tabInactive: "text-slate-600 hover:text-slate-900 hover:bg-white/35",
    divider: "border-white/28",
    sheen: "",
    glassIcon: "glass-icon",
  },
  dark: {
    accent: "#34d399",
    appBg: "bg-zinc-950",
    headerCls: "glass-header-dark",
    blockCls: "glass-dark",
    blockHd: "glass-bar-dark text-zinc-100",
    blockBtn: "bg-white/8 hover:bg-white/15 text-white border border-white/10",
    tblHead: "bg-white/5 text-zinc-400 border-b border-white/7",
    tblRow: "bg-white/3 border-b border-white/5",
    tblHover: "hover:bg-white/9",
    formCard: "glass-dark rounded-xl",
    formLabel: "text-zinc-300",
    inputCls: "bg-white/7 border-white/11 text-zinc-100 focus:ring-emerald-500 focus:bg-white/13",
    modalCls: "glass-modal-dark",
    overlay: "bg-black/48 backdrop-blur-sm",
    textPri: "text-zinc-100",
    textSec: "text-zinc-400",
    textMut: "text-zinc-600",
    accentText: "text-emerald-400",
    btnPri: "bg-emerald-700 hover:bg-emerald-600 text-white shadow-sm shadow-emerald-900/20",
    btnSec: "bg-white/8 hover:bg-white/15 text-zinc-100 border border-white/10",
    btnGreen: "bg-emerald-700 hover:bg-emerald-600 text-white shadow-sm shadow-emerald-900/20",
    btnDanger: "bg-rose-500/12 hover:bg-rose-500/22 text-rose-400 border border-rose-500/28",
    tabActive: "bg-emerald-700 text-white shadow-sm shadow-emerald-900/25",
    tabInactive: "text-zinc-400 hover:text-zinc-100 hover:bg-white/8",
    divider: "border-white/9",
    sheen: "",
    glassIcon: "glass-icon-dark",
  },
};
